In [64]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.svm import LinearSVC
from sklearn.metrics import confusion_matrix, classification_report, f1_score
from sklearn.preprocessing import MinMaxScaler

In [48]:
df = pd.read_csv('UNSW_NB15_training-set.csv')
df.set_index('id', drop=True, inplace=True)

In [49]:
df.head(10)

dur proto service state  spkts  dpkts  sbytes  dbytes          rate  \
id                                                                             
1   0.000011   udp       -   INT      2      0     496       0   90909.09020   
2   0.000008   udp       -   INT      2      0    1762       0  125000.00030   
3   0.000005   udp       -   INT      2      0    1068       0  200000.00510   
4   0.000006   udp       -   INT      2      0     900       0  166666.66080   
5   0.000010   udp       -   INT      2      0    2126       0  100000.00250   
6   0.000003   udp       -   INT      2      0     784       0  333333.32150   
7   0.000006   udp       -   INT      2      0    1960       0  166666.66080   
8   0.000028   udp       -   INT      2      0    1384       0   35714.28522   
9   0.000000   arp       -   INT      1      0      46       0       0.00000   
10  0.000000   arp       -   INT      1      0      46       0       0.00000   

    sttl  ...  ct_dst_sport_ltm  ct_dst_src_ltm  is_ftp_login  ct_ftp_cmd  \
id        ...                                                               
1    254  ...                 1               2             0           0   
2    254  ...                 1               2             0           0   
3    254  ...                 1               3             0           0   
4    254  ...                 1               3             0           0   
5    254  ...                 1               3             0           0   
6    254  ...                 1               2             0           0   
7    254  ...                 1               2             0           0   
8    254  ...                 1               3             0           0   
9      0  ...                 2               2             0           0   
10     0  ...                 2               2             0           0   

    ct_flw_http_mthd  ct_src_ltm  ct_srv_dst  is_sm_ips_ports  attack_cat  \
id                                                                          
1                  0           1           2                0      Normal   
2                  0           1           2                0      Normal   
3                  0           1           3                0      Normal   
4                  0           2           3                0      Normal   
5                  0           2           3                0      Normal   
6                  0           2           2                0      Normal   
7                  0           2           2                0      Normal   
8                  0           1           3                0      Normal   
9                  0           2           2                1      Normal   
10                 0           2           2                1      Normal   

    label  
id         
1       0  
2       0  
3       0  
4       0  
5       0  
6       0  
7       0  
8       0  
9       0  
10      0  

[10 rows x 44 columns]

In [50]:
str_dtypes = tuple(filter(lambda t: t[1] not in (np.dtype('int64'), np.dtype('float64')), df.dtypes.to_dict().items()))

In [51]:
str_dtypes

(('proto', dtype('O')),
 ('service', dtype('O')),
 ('state', dtype('O')),
 ('attack_cat', dtype('O')))

In [52]:
str_cols = dict(str_dtypes).keys()

In [53]:
df.drop(str_cols, axis=1, inplace=True)

In [54]:
X = MinMaxScaler().fit_transform(df.iloc[:, :-1])
y = df.iloc[:, -1]

In [55]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=.3, random_state=1)

In [56]:
model = LinearSVC(random_state=1, C=0.11, max_iter=1000, dual=False)

In [57]:
model.fit(X_train, y_train)

LinearSVC(C=0.11, dual=False, random_state=1)

In [58]:
round(model.coef_[0, 4], 2)

-1.14

In [59]:
y_pred = model.predict(X_test)

In [62]:
confusion_matrix(y_test, y_pred)

array([[ 8868,  2125],
       [ 1473, 12234]], dtype=int64)

In [63]:
print(classification_report(y_test, y_pred, digits=3))

              precision    recall  f1-score   support

           0      0.858     0.807     0.831     10993
           1      0.852     0.893     0.872     13707

    accuracy                          0.854     24700
   macro avg      0.855     0.850     0.852     24700
weighted avg      0.854     0.854     0.854     24700



In [65]:
f1_score(y_test, y_pred, average='macro')

0.8515756004587374

In [75]:
X[14001, :]

array([1.66666697e-07, 9.39408173e-05, 0.00000000e+00, 6.26926493e-06,
       0.00000000e+00, 1.00000002e-01, 9.96078431e-01, 0.00000000e+00,
       8.65603603e-03, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       1.66638916e-07, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 2.22972973e-02,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 5.80645161e-01,
       3.33333333e-01, 6.20689655e-01, 6.20689655e-01, 3.78378378e-01,
       5.80645161e-01, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       6.10169492e-01, 5.90163934e-01, 0.00000000e+00])

In [76]:
model.predict([_])

array([1], dtype=int64)

In [77]:
model.predict([X[18512]])

array([1], dtype=int64)